#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-formatador
Version  : 0.2.5
Release  : 9
URL      : https://rubygems.org/downloads/formatador-0.2.5.gem
Source0  : https://rubygems.org/downloads/formatador-0.2.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-shindo

%description
= formatador
STDOUT text formatting
== Quick and dirty
You can call class methods to print out single lines like this:

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n formatador-0.2.5
gem spec %{SOURCE0} -l --ruby > rubygem-formatador.gemspec

%build
gem build rubygem-formatador.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
formatador-0.2.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/formatador-0.2.5 && RUBYOPT=-I.:lib shindo && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/formatador-0.2.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/CONTRIBUTORS.md
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/LICENSE.md
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/changelog.txt
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/formatador.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/lib/formatador.rb
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/lib/formatador/progressbar.rb
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/lib/formatador/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/tests/basic_tests.rb
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/tests/table_tests.rb
/usr/lib64/ruby/gems/2.3.0/gems/formatador-0.2.5/tests/tests_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/formatador-0.2.5.gemspec
